### ISSUE TITLE
XDG

### ISSUE THREAD

**Issue by gutierri** [abusque/ratpoison#1]
It seems to be interesting to follow the XDG standard for file history and configuration file

**Comment by gutierri** [comment]
I implemented this in my git tree(1c87f87674f031d814c9e1744df3bb6932dc6873). If they agree, I can make a "Pull Request";

**Comment by abusque** [comment]
Hi!

First of all, thanks for contributing to ratpoison. However, this repository is an "unofficial" repository, because I'm just a user/contributor like you. The [official ratpoison repository](http://git.savannah.nongnu.org/cgit/ratpoison.git) is hosted on Savannah rather than GitHub.

If you want to submit your patch for discussion and eventually integration into the official ratpoison repository, you will have to send it the the development mailing list, [ratpoison-devel](https://lists.nongnu.org/mailman/listinfo/ratpoison-devel) (you might also be interested by the [archives](http://lists.nongnu.org/archive/html/ratpoison-devel/)). I don't know if you're familiar with submitting patches via email, so here are some [instructions on using git send-email](https://www.freedesktop.org/wiki/Software/PulseAudio/HowToUseGitSendEmail/). Other options are available, and you can almost certainly find instructions online for your specific email client, although some are easier to use for this than others.

If you have any questions, don't hesitate to join the IRC channel `#ratpoison` on the server `irc.freenode.net`.

As for your patch itself, I took a look at it and, while I'm not sure if ratpoison wants to support XDG-style configuration directories (that'll be up to the community and the maintainer to decide after discussion on the mailing list), I noticed at least one issue: on line 626 in `src/globals.c`, `if (mkdir == -1)` should almost certainly be `if (mkdir_status == -1)`. In terms of coding style too you'll want to stay consistent and leave a space between the function name and the parentheses when calling it. There are other minor things like a comment in `main.c` mentioning `.ratpoisonrc` instead of the new name (without the `.` prefix). I haven't yet tried building and running it though, so there might be other things I missed. I can give a full review once you send it to the mailing list, if necessary.

I'll be closing the issue here, but if for some reason you can't comment on IRC or the mailing list, feel free to write back here.

Best regards,
Antoine.

**Comment by gutierri** [comment]
@abusque could we not keep development parallel here?

**Comment by abusque** [comment]
This is my personal development repository that I leave public for my own convenience, but no one else uses it. It's not my intention to fork or diverge from the official repository, so I'd rather not take in pull requests. Your best bet is to go through the mailing list.
